### PR TITLE
Fix/issue98_99

### LINKED ISSUE #98: Lines may not be divided correctly due to approximations
**Minimal Test Case** : 
Activate any grid (the basic 4x4 grid works fine)
Draw a diagonal Line from point (-200,-200) to point (200,200)
Draw an horizontal line from point (0,200) to (0,0)

**Expected result** : The diagonal line should be divided into two lines, since the point (0,0) is on the line.

**Result** : The diagonal is not divided

**Workaround** : draw a line that's longer than needed and delete the excess afterwards

**Analysis** : The calculation of wether the line should be divided or not is made by the `RectangleClipper` class, called from the `LineAdder::addAll` method
This class builds a rectangle around the newly added line to do the clipping, adding a slight amount to each coordinates (`POINT_EPS = 1.0E-5`), to avoid problems due to approximations in calculations (?)
then, the `clipTest` method of `RectangleClipper` returns `false`, but should return `true`.
This seems to be due to approximations made in the `calcClippedPoint` method.
If I understand correctly, we calculate the `y` coordinate on the diagonal, for the `m_minX` (`=-1.0E-5`) abscissa... the result should be the same, since this is a diagonal, but the approximations made by the calculation brings a value of `-1.0000000003174137E-5`, which is unfortunately outside of the clipping rectangle...

**Possible solutions** : 
- The approximation goes clearly too far and could be considered equal to `-1.0E-5`
- Instead of testing the affine function at the `m_minX` abcsissa, we could test it at `m_minX + POINT_EPS`, which is the coordinate that should really be tested (I think this would be a cleaner solution mathematically speaking, since it really is the point we input in the first place. The small epsilon that has been added before is still relevant and should still be in the `if ((cy >= m_minY) && (cy <= m_maxY))` test)

### PR DESCRIPTION
**Pull request by lifesbest23**
This should resolve the problem of #100, even though it is not optimized.
I am trying to merge master into my branch but I have to do it manually so it might take some time. If you know a better way, let me know. If something else is needed as well.

should close #98 #99

### CODE REVIEW

File: src/test/java/oripa/domain/cptool/LineAdderTest.java [hunk 1]
```diff
@@ -34,40 +37,131 @@
...
+
+		// When
+		adder.addLine(line, creasePattern);
+
+		// Then
+		assertEquals(7, creasePattern.size());
+
+		var lastX = -200;
+		for (int x = -100; x <= 150; x += 50) {
+			assertTrue(creasePattern.contains(new OriLine(lastX, 0, x, 0, OriLine.Type.MOUNTAIN)));
```
Comment (Ooouch1) [inline src/test/java/oripa/domain/cptool/LineAdderTest.java:147]: `Collection::contains` doesn't care epsilon of `double`. That might cause a failure of this test if the implementation of `LineAdder::add` is correct.

File: src/test/java/oripa/domain/cptool/LineAdderTest.java [hunk 2]
```diff
@@ -34,40 +37,131 @@
...
+						new OriLine(0, 0, 50, 0, OriLine.Type.VALLEY),
+						new OriLine(100, 0, 150, 0, OriLine.Type.VALLEY) }));
+
+		var line = new OriLine(-200, 0, 200, 0, OriLine.Type.MOUNTAIN);
+
+		// When
+		adder.addLine(line, creasePattern);
+
+		// Then
+		assertEquals(7, creasePattern.size());
```
Comment (Ooouch1) [inline src/test/java/oripa/domain/cptool/LineAdderTest.java:143]: According to the result of test, this line fails and `LineAdder::addLine` is not correct.

File: src/test/java/oripa/domain/cptool/LineAdderTest.java [hunk 3]
```diff
@@ -34,40 +37,131 @@
...
+		var creasePattern = new ArrayList<>(List.of(new OriLine(0, 0, 200, 0, OriLine.Type.VALLEY)));
+		var line = new OriLine(0, 0, 100, 0, OriLine.Type.VALLEY);
+
+		// When
+		adder.addLine(line, creasePattern);
+
+		// Then
+		assertEquals(2, creasePattern.size());
+		assertTrue(creasePattern.contains(new OriLine(0, 0, 100, 0, OriLine.Type.VALLEY)));
+		assertTrue(creasePattern.contains(new OriLine(100, 0, 200, 0, OriLine.Type.VALLEY)));
```
Comment (Ooouch1) [inline src/test/java/oripa/domain/cptool/LineAdderTest.java:94]: According to the result of tests, this line fails. `Collection::contains` might not be appropriate for the test.

**Review by Ooouch1 — CHANGES_REQUESTED** [review]
The tests fail.

File: src/test/java/oripa/domain/cptool/LineAdderTest.java (hunk 1 above)
Comment (lifesbest23) [reply src/test/java/oripa/domain/cptool/LineAdderTest.java:147]: That is a good find, I was trying to fix the failing test, but somehow missed the that there is no epsilon taken into account for the `OriLine.equals` function (or rather `OriPoint.compareTo` since that is used for comparing lines). That should be the case though, right?

File: src/test/java/oripa/domain/cptool/LineAdderTest.java (hunk 2 above)
Comment (lifesbest23) [reply src/test/java/oripa/domain/cptool/LineAdderTest.java:143]: Yes, that corresponds to in program testing I have done, not sure if this relates to not having an EPS for `OriLine.equals` since lines get removed from a list utilizes that.

**Comment by lifesbest23** [comment]
I somehow messed up the `GeomUtil.areOnSameSupportLine()` function while merging with the current master, turns out this fixes all the problems. Took me a while to figure that out.

> there is no epsilon taken into account for the `OriLine.equals `function (or rather `OriPoint.compareTo` since that is used for comparing lines). That should be the case though, right?

This point did not seem to be the problem, but I think it should still be implemented in that way, and if it was, it would make the usage of `List.contains` and other tests relying on comparing `OriLine` viable, even with floating points precision inaccuracy.

Another question I have is whether the private functions I added to `GeomUtil` for Segments (`segmentIsVertical` and `getAffineX/YValueAt`) should be added to the `Segment` class instead?

File: src/test/java/oripa/domain/cptool/LineAdderTest.java (hunk 3 above)
Comment (lifesbest23) [reply src/test/java/oripa/domain/cptool/LineAdderTest.java:94]: lifesbest23@66effa7321b07a0ada28ce818f833ec80453bb3a should resolve this. Regarding your question, I have added something below.

File: src/test/java/oripa/domain/cptool/LineAdderTest.java (hunk 2 above)
Comment (lifesbest23) [reply src/test/java/oripa/domain/cptool/LineAdderTest.java:143]: lifesbest23@66effa7321b07a0ada28ce818f833ec80453bb3a should resolve this.

File: src/test/java/oripa/domain/cptool/LineAdderTest.java (hunk 1 above)
Comment (lifesbest23) [reply src/test/java/oripa/domain/cptool/LineAdderTest.java:147]: `LineAdder::addLine` was faulty.
lifesbest23@66effa7321b07a0ada28ce818f833ec80453bb3a should resolve this.

**Comment by Ooouch1** [comment]
>> there is no epsilon taken into account for the OriLine::equals function (or rather OriPoint::compareTo since that is used for comparing lines). That should be the case though, right?

> This point did not seem to be the problem, but I think it should still be implemented in that way, and if it was, it would make the usage of Collection::contains and other tests relying on comparing OriLine viable, even with floating points precision inaccuracy.

I think `equals` method should be always strict because it affects behavior of hash set/map. If we introduce epsilon into `equals`, maybe the conditions of `hashCode` will be broken. Adding `nearlyEquals(that, eps)` to `OriLine` or `Segment` might make coding comfortable: We can write `oriLines.stream().anyMatch(l -> someLine.nearlyEquals(l, eps))` instead of `oriLines.contains(someLine)`.

> Another question I have is whether the private functions I added to GeomUtil for Segments (segmentIsVertical and getAffineX/YValueAt) should be added to the Segment class instead?

Implementing as Segment's methods seems more object-oriented way which I like. In that way, we can remove duplications of `isVertical`/`getAffineXValueAt`/`getAffineYValueAt` in `GeomUtil` and `OriLine`.

File: src/main/java/oripa/geom/GeomUtil.java [hunk 4]
```diff
@@ -473,16 +451,67 @@ private static double computeCCW(final Vector2d p0, final Vector2d p1, final Vec
...
 	public static Vector2d computeCentroid(final Collection<Vector2d> points) {
 		var centroid = new Vector2d();
-		points.forEach(p -> centroid.add(p));
+		points.forEach(centroid::add);
 		centroid.scale(1.0 / points.size());
 
 		return centroid;
 	}
+
+	public static boolean detectOverlap(final Segment existingLine, final Segment newLine) {
```
Comment (Ooouch1) [inline src/main/java/oripa/geom/GeomUtil.java:466]: If we make `OverlappingLineExtractor::isOverlap` public, I think this method can be removed by replacing method calls.

File: src/main/java/oripa/geom/GeomUtil.java [hunk 5]
```diff
@@ -26,36 +29,22 @@
...
 import javax.vecmath.Vector2d;
 
-public class GeomUtil {
-	// private static final Logger logger =
-	// LoggerFactory.getLogger(GeomUtil.class);
+import oripa.value.CalculationResource;
 
-	public final static double EPS = 1.0e-6;
+public class GeomUtil {
+	public final static double EPS = CalculationResource.POINT_EPS;
```
Comment (Ooouch1) [inline src/main/java/oripa/geom/GeomUtil.java:35]: I'm not sure this change is good or not. `CalculationResource.POINT_EPS` is `1e-5`, which is larger than the old value of this `EPS`.

**Review by Ooouch1 — COMMENTED** [review]
Overwriting line type works but can be slow if the crease pattern is massive. The performance problem should be another issue. I have an idea which was written as a pseudo code here: https://github.com/oripa/oripa/issues/99#issuecomment-833414257

Some refactoring can be done.

**Comment by lifesbest23** [comment]
Thank you very much for the in depth review and the algorithm suggestion, it will take some time for me to eventually implement the improved algorithm, but I do agree that a lot of refactoring should be done, and is probably the easier part.

I might refactor some other stuff in `OriLine` as well since this class seems pretty messy. But I will try to remain inside the context of this pull request.

File: src/main/java/oripa/geom/GeomUtil.java (hunk 5 above)
Comment (lifesbest23) [reply src/main/java/oripa/geom/GeomUtil.java:35]: The bigger epsilon would only affect grid sizes around 400/1e-5=4e7 but should indeed be held as small as possible.
The global `CalculationResource.POINT_EPS` value could be updated, though I am not sure if that would brake anything.
Will try and at some point.

**Comment by Ooouch1** [comment]
I found a bug in the pseudo code of my algorithm...
I'm ready to fix and implement it so you don't have to rush to implement it. That should be in another PR.

**Review by Ooouch1 — APPROVED** [review]
It works fine.
